### ISSUE TITLE
Problem: Email capture includes developers

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1004]
Problem: We have a single email capture that grabs emails on every page. A subset of those subscribers are developers and it would be useful to separate them so we can send specific developer emails. 

Proposal: Anyone who enters email on blockstack.org we signup for both general ecosystem updates and technical/developer updates. Assuming we can signup for both lists, and the user can specifically unsubscribe from one or both as desired. I've seen this behavior before where as a user I can turn off specific lists. Confirming this is possible @cuevasm? Any better ideas?

**Comment by cuevasm** [comment]
I would generally prefer not subscribe people to multiple lists upon joining because they aren't asking for that and it's a better look for Blockstack to be overly careful about what subscription to one thing means and how far we take that, that said, some of my issue there could be solved with the right messaging. 

More importantly though, when you mix subscribers, but then the list content isn't generic (ala technical updates), you end up not knowing if your content is working. We'll see a lot of unsubscribes and dormant folks, but we won't know if it's because the content isn't right or if we just have a bunch of irrelevant subscribers on.

I'd prefer they be given the choice right up front and it made clear which list they are being put on. I think a simple checkbox for "I'm a Developer" solves this and other easy methods like, if they subscribe from the docs or a clearly dev heavy place, we put them on a developer list.
