### ISSUE TITLE
Job Postings not updated on the Career page

### ISSUE THREAD

**Issue by thaonguyenle** [blockstack/blockstack.org#1126]
**Describe the bug**
When I go to https://blockstack.org/careers , the Director of Strategic Partnership/BD role is not listed on there. Or I can't see it. Same with Muneeb and Lauren. We were able to see it last week. However, Tom can see this role on his computer. 

The role can be always be viewed here: https://jobs.lever.co/blockstack/d0b61b97-d8d7-446e-889b-7c6e8742521e. But. I don't want to post a tweet linking people to that, instead of our career page

We should have everyone be able to view these job descriptions on the career page. 

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Chrome
 

**Additional context**
I'm trying to get Muneeb to post this JD on his Twitter soon so I would really appreciate this done soon-ish.

**Comment by wileyj** [comment]
https://api.lever.co/v0/postings/blockstack?mode=json

https://github.com/blockstack/blockstack.org/blob/master/common/es6/index.js#L106-L131

the missing job posting has a `/` char.

**Comment by markmhx** [comment]
@aulneau can you confirm this role isn't getting imported due to the slash, and if so, whether there's a simple fix?

**Comment by aulneau** [comment]
@markmhx as I stated in my email, the website fetches the jobs data at build time each time we deploy the site. That means that if there are jobs added to lever after a deployment, the data will not exist on the site until a redeployment happens. I just tested it locally, and these are the jobs I see:
![Screen Shot 2020-07-08 at 9 20 05 AM](https://user-images.githubusercontent.com/11803153/86930206-61017b00-c0fc-11ea-8a90-fec90ea51703.png)

Part of why this is the case is because for a long time, we as a company didn't want the site to be able to be updated without our knowledge, and as such, we went the route of doing a [static export](https://nextjs.org/docs/advanced-features/static-html-export) of the site for each deployment. There have been a lot of improvements to next.js, such as [Incremental Static Regeneration](https://nextjs.org/blog/next-9-4#incremental-static-regeneration-beta), which the ui docs use and new docs will use, but because we are moving away from next.js for blockstack.org, that was never implemented.

Anyways, that's all to say that if there is a new job posting, we only have to as someone from devops to initiate a redeployment of the site and it will fetch the latest data from lever. 

> However, Tom can see this role on his computer.

To be honest I have no idea why this would be the case. 

@wileyj could you do a fresh deployment of blockstack.org? That should resolve this issue.

**Comment by markmhx** [comment]
Got it, I figured this was a separate issue since the other three are here, but that makes sense 👍

**Comment by thaonguyenle** [comment]
But I'm pretty sure I saw it last week? is that not real (what I saw? Maybe
I was imagining it?)

Thanks @wileyj for doing this. Pls let me know when it's ready.

**Comment by markmhx** [comment]
👻's in the machine...

**Comment by kantai** [comment]
For those that are curious -- for exactly the reasons that @aulneau mentioned, there's the potential for a skew between the static exports and dynamically constructed pages on the site, so if you go to blockstack.org and the click about->careers from the home page, you should see a dynamically fetched list of jobs (with the new listing), but if you refreshed the page, you'd see the static build (without the new listing)

**Comment by wileyj** [comment]
I would argue that this process should be changed. 
i don't think we should have to rebuild the site every time a listing is changed - it requires more process, and if a role is added/removed it requires someone to rebuild the site again. 

at the very least, for this json fetch i think it would suit us better to simply retrieve the data when the `/careers` endpoint is requested.

**Comment by markmhx** [comment]
This process is getting changed with the move to Webflow next week, so I think we just need one last rebuild here to fix the missing role for the next several days.

**Comment by markmhx** [comment]
This has been resolved
