### ISSUE TITLE
Clarity messaging: Algorand partnership

### ISSUE THREAD

**Issue by agraebe** [blockstack/blockstack.org#1128]
Would it make sense to mention that Clarity is a project driven by Algorand and Blockstack? Something to highlight that Clarity is maintained and maturing fast because of two "ecosystem players" involved? Maybe also link to the Clarity lang page somewhere?

**Comment by markmhx** [comment]
@muneeb-ali thoughts here on how much we should highlight the separate Clarity website on PBC's website? And mention Algorand and other ecosystem partners vs. leaving that to the Stacks ecosystem's properties?

**Comment by jasperjansz** [comment]
I don't think our audience is familiar with Algorand. We'd have to link to them for it to make sense — which we should not do because they are a competitor. I am now linking to the Clarity website in-line though and I'm referencing that it has been adopted by multiple projects in the space without mentioning names.
