### ISSUE TITLE
talk about blockchain agnostic (layer 2) on home page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#286]
@pstan26 @larrysalibra @shea256 @muneeb-ali 

One of our biggest selling points is that Blockstack is blockchain agnostic and that we are a flexible platform that is not pinned to one blockchain. We are not saying / visualizing this on the home page.

**Comment by pstan26** [comment]
Believe we must be *very* carefully word this. You may already agree saying agnostic alone is not enough, as it sounds like we could care less which blockchain we work on. Think it would be wise to point out which characteristics we value in the blockchain our virtualchain lives on and that we can move from one to another (perhaps making an allusion to VMs) as opposed to trying to be all things to all people.

**Comment by larrysalibra** [comment]
This is a great point @pstan26

It's also important to make clear which characteristics of the underlying blockchain are inherited by Blockstack.

**Comment by guylepage3** [comment]
all great points guys.. i still feel that our system architecture is our market separator though.

i definitely would like to hear from others on this topic...

@shea256 @muneeb-ali @jcnelson @kantai @vsund @itsProf @john-light

**Comment by john-light** [comment]
@guylepage3 start with your customers/ users. Who is your target customer/user, what problem(s) are you solving for them, what are their values? Answering these questions will help you determine what features to focus your messaging on.

**Comment by estermer** [comment]
I am wonder how important it is to add this to the homepage? Considering @john-light 's comment, I am not sure this is really too much in the mind of the common user, This seems to me to be a FAQ or a Blockstack Academy type Question/Answer rather than a home page spotlight item. I could be wrong though.

If it is important enough, could the terminology be changed to flexibility.

For example: "Blockstack is flexible and not fixed to any single underlying blockchain."

or " Blockstack is unbound from running a single blockchain."
