### ISSUE TITLE
section 2 content of home page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#287]
Currently we are saying;

"The decentralized internet is already here"

as a headline in the second section of the home page

<img width="1920" alt="screenshot 2017-04-19 17 44 50" src="https://cloud.githubusercontent.com/assets/1711854/25203652/fe36843e-2527-11e7-90dc-d7c0475dbada.png">

I feel this doesn't mean much to me and that we need to say that it's currently working. ie.

"Unlike other platforms where developers cannot build apps, Blockstack is a working system where developers can build apps, Today!"

Thoughts?

**Comment by estermer** [comment]
I should get my wife in on this, she is good at copywriting... but she probably wouldn't understand a thing about what is going on hahaha!

I agree though it seems a little thin maybe? 

I am not sure about the suggestion of yours if you going for something leading into the three points below it.

Maybe just get rid of "already" from it? I think it is a little more declarative.

**Comment by pstan26** [comment]
some more options to keep momentum in this thread:

- "the decentralized internet on blockstack works today" <-declarative and staking claim of where it is

- "did you hear the good news? the decentralized internet on blockstack is here" <- a little more gospel

**Comment by vsund** [comment]
I don't know how much you discussed what content (thinking of concepts to be applied) you want to use. So if the type of concept already got discussed and is out of scope, please forgive me :D

The abstract problem is that users should recognize that Blockstack isn't just another ambitious idea on how to make everything™️ better; but more a platform that is in production since 2 years, ready for in-production use and is making big fast-paced steps forward all the time.

I see a few different possibilities to communicate that, where a plain text description is only one of many.

* Give examples what already runs on Blockstack
  * Could be apps (needs some more time because not much "Blockstack apps" are currently here)
  * But also services that integrated Blockstack (thinking of OpenBazaar, Mediachain, ...)
    * Works the best with evidence :)
* Bring interested developers as fast as possible into playing around with Blockstack
  * Maybe a call-to-action button with a "Start building on the decentralized internet now" which takes you to a developer playground where you can get a feeling for what's possible and so on.
  * https://developer.uport.me is a kind of playground, we could definitely do something similar
* Communicate the growth of the network over time
  * Provide some catchy graphs (the numbers which are currently on the page let you get a sense how big it is, but not how fast it grows)
  * Maybe a timeline of events would help too. Communicates easily what's going on, where Blockstack is currently and especially how active it is atm (heavily linked @pstan26's roadmap thoughts)
* Plain text description
  * With just text it's more harder to get the same results, I guess
  * Maybe simply stating that "Blockstack isn't just an idea, it's a well-matured platform that enables you to decentralize your app straightaway"

**Comment by guylepage3** [comment]
>I should get my wife in on this, she is good at copywriting... but she probably wouldn't understand a thing about what is going on hahaha!

Hahaha.. yeah a bit tough to grasp

>"the decentralized internet on blockstack works today"

I really like that. but maybe something a bit more smooth. **"Blockstack is working today and it's here to stay"**?

>I don't know how much you discussed what content (thinking of concepts to be applied) you want to use. So if the type of concept already got discussed and is out of scope, please forgive me :D

@vsund these are all very good points that you bring up. one of the things we are trying to communicate on the home page is that the project is a) working today and b) it will be around for a long, long time.

We also want to communicate this in a very short one line as the user will be scrolling through more of the content as you currently see on blockstack.org..

![screencapture-blockstack-org-1493309136438](https://cloud.githubusercontent.com/assets/1711854/25492722/e79d5f7a-2b41-11e7-9886-d03d66ed07e5.png)

**Comment by guylepage3** [comment]
resolved here: [#302: home page content](https://github.com/blockstack/blockstack.org/issues/302)
