### ISSUE TITLE
Home Page - Goals and Visuals

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack.org#299]
This is a draft for the various goals and visuals for the blockstack.org home page. At @guylepage3's request, I put this document together. Welcoming any and all comments.

### Hero Section
- Primary goal: Get developers to feel a desire to build apps on Blockstack.
- Secondary goal: Collect emails for people who want to try Blockstack. For those who are developers, email them a download link. For those who are not, tell them we will update them when the user-facing software is ready.
- Tertiary goal: Get developers to watch the tutorial.
- Visual goal: Give developers a visual that gets them to instantly understand and visualize how decentralized apps work. They don’t have any central parties or command-and-control system. One idea is to show a decentralized network of Uber-like cars and Airbnb-like homes that are all communicating with one another in a peer-to-peer fashion.

### Vision Section
- Primary goal: Convey that the internet is broken today and how it could be better. Show the reasons why it is broken and for every one of these reasons, show a remedy to the problem.
- Visual goal: Draw a sharp contrast between the broken internet of today and the safe and free internet of tomorrow. 

### Benefits Section
- Primary goal: Sell the developer on why one should build apps on Blockstack. The reader has gotten this far and wants to be convinced. The developer wants to be inspired.
- Visual goal: Paint a picture for the developer of what building on Blockstack will be like. It is less work and more money and it’s better for users and society.

### Features Section
- Primary goal: Explain exactly what Blockstack provides. Up until this point, the developer only has an abstract concept of building on Blockstack. The developer does not yet know what services will be provided. The developer cannot yet picture the functions that will be called and the API endpoints that will be hit.
- Visual goal: Show that developers get everything they need to build a decentralized app from start to finish. This should convey that we’ve got developers covered.

### App Section
- Primary goal: This should get developers to start imagining the apps that they could build on top of Blockstack. We want to go really big here. The more ambitious and unconventional the better. These are not necessarily the apps we actually want people to build on the platform. They are apps that should make people stop and think “Whoa I didn’t even think that could be built. Blockstack makes this possible?”
- Visual goal: Illustrate the various apps that could be built on Blockstack. Get people really thinking about what they can build. Get them dreaming and imagining.

### Tutorial Section
- Primary goal: This should get users to click through to the tutorial. They should be enticed into trying it out.
- Visual goal: Show a preview of the tutorial.

### News Section
- Primary goal: Show visitors that this is an active project that is improving rapidly.
- Visual goal: Make it easy to preview the recent updates.

**Comment by guylepage3** [comment]
This is awesome! Thanks @shea256...

**Comment by guylepage3** [comment]
## Blockstack.org home view goals (Round 2)

### Home view goals
**Primary goal** – 
**Secondary goal** – 
**Tertiary goal** – 
** Visual goal** – 


### Hero section goals
**Primary goal** – Captive the user so that they do not bounce off the site
**Secondary goal** – Capture the user's email address in one of two buckets; 1) Users of Blockstack 2) Developers who build or contribute to Blockstack.
**Tertiary goal** – Entice the user to inquire to learn more about Blockstack
** Visual goal** – To give the user a sense of new technology that is highly innovative, unique, mysterious. The visual must captivate the user enough to accomplish the **primary goal**.

**Comment by guylepage3** [comment]
## Blockstack.org home view goals (Round 2)

### Home view goals
- **Primary goal** – 
- **Secondary goal** – 
- **Tertiary goal** – 
- **Visual goal** – 

### Hero section goals
- **Primary goal** – Captive the user so that they do not bounce off the site
- **Secondary goal** – Capture the user's email address in one of two buckets; 1) Users of Blockstack 2) Developers who build or contribute to Blockstack.
- **Tertiary goal** – Entice the user to inquire to learn more about Blockstack
- **Visual goal** – To give the user a sense of new technology that is highly innovative, unique, mysterious. The visual must captivate the user enough to accomplish the **Hero section primary goal**.

**Comment by guylepage3** [comment]
pinning... [#302: Quick new layout of blockstack.org home page with new content](https://github.com/blockstack/blockstack.org/issues/302)

**Comment by guylepage3** [comment]
@shea256 closing out this issue
