### ISSUE TITLE
home page content

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#302]
Quick new layout of blockstack.org home page with new content

**Comment by guylepage3** [comment]
![home-hero](https://cloud.githubusercontent.com/assets/1711854/26028388/6511356e-37ed-11e7-89b4-fc3654aee1bd.png)

**Comment by guylepage3** [comment]
New temp hero..

![home-hero 1](https://cloud.githubusercontent.com/assets/1711854/26028432/2e149410-37ee-11e7-84f1-8d355039c7ff.png)

**Comment by guylepage3** [comment]
@shea256 can you copy and paste the content from the hero visual into this issue for me please? Thanks.

**Comment by shea256** [comment]
Blockstack

Install, Tutorials, Blog, Papers, Videos

Build Decentralized Apps

Blockstack is a new decentralized internet where users own their data and where apps run locally without remote servers.

71,861
users registered

3+
years in production

15,392
github commits

Users
Join the Waitlist

Developers
Get the Developer Kit

**Comment by guylepage3** [comment]
@shea256 shouldn't we change the wording for developers on mobile? We want them to think they can sign up when they're on their mobile devices so that we capture their details to send them the kit to their inbox. The way it's worded now "Get the Developer Kit" doesn't explicitly say what happens when they click the button. "Join the waiting list" for users works on mobile as it sounds like we're taking them to a form for them to join.

Thoughts?

<img width="517" alt="screenshot 2017-05-13 15 47 33" src="https://cloud.githubusercontent.com/assets/1711854/26028672/81422ab2-37f3-11e7-8e65-f8340e96be76.png">

**Comment by shea256** [comment]
OK it should still be very clear that:

- Users -> Join the Waitlist
- Developers -> Get the Developer Kit

And I was thinking the developers would click through and assume they're going to be sent something.

**Comment by guylepage3** [comment]
A solution could be that on mobile, we treat everyone the same and have a third sign up page that pushes everyone to a page that splits up the two demographics where we can provide them with more of a description of the content;

### 3rd sign up page

**Users**
Be the first to get notified when Blockstack becomes available to the public
Button: [Get notified]

**Developers**
Join thousands of developers and get the developer kit by via email
[Get the Developer Kit]

**Comment by guylepage3** [comment]
A solution could be that on mobile, we treat everyone the same and have a third sign up page that pushes everyone to a page that splits up the two demographics where we can provide them with more of a description of the content;

### 3rd sign up page

**Users**
Be the first to get notified when Blockstack becomes available to the public
Button: [Get notified]

**Developers**
Join thousands of developers and get the developer kit by via email
Button: [Get the Developer Kit]

**Comment by shea256** [comment]
OK we could do this but I'd prefer to not have so many pages. Is it possible to do something simpler? Fit the desktop copy on screen?

**Comment by guylepage3** [comment]
>Is it possible to do something simpler?

I will think of something..

>Fit the desktop copy on screen?

No. There's just to much content and the button would appear below the fold on mobile devices.

See example below
<img width="457" alt="screenshot 2017-05-13 16 24 24" src="https://cloud.githubusercontent.com/assets/1711854/26029015/31182ca2-37f9-11e7-8e24-902ba984b29e.png">

**Comment by guylepage3** [comment]
From slack

Guy Lepage [4:34 PM] 
I feel there should only be one button for mobile. That will be the high majority of people discovering blockstack at the upcoming events

[4:35] 
We should cater to those people and make sure that we properly guide them down the right funnel.

Ryan Shea [4:35 PM] 
ok let's go with one button for now

[4:36] 
we can always change the button copy

Guy Lepage [4:36 PM] 
it also allows us to execute a simple call to action while you guys are on stage

Ryan Shea [4:36 PM] 
but let's try "get invited" on that one button

Guy Lepage [4:36 PM] 
sounds good

**Comment by guylepage3** [comment]
@shea256 here's an article about creating a better ux for users on mobile. the TLDR; is that we should not include ALL the sections we have on the home page so that users on mobile can get to where they want to go quickly and easily. We don't necessarily have to apply this concept to this initial quick and dirty version but the concept does have merit.

https://www.viget.com/articles/do-responsive-sites-have-to-be-so-tall-on-mobile

**Comment by guylepage3** [comment]
@shea256 i am pulling this section out of the hero section as it does not assist in getting the user to click the button.

<img width="789" alt="screenshot 2017-05-13 17 11 28" src="https://cloud.githubusercontent.com/assets/1711854/26029300/be7321be-37ff-11e7-9af3-cb1ceea597f3.png">

maybe it can be it's own section? thoughts?

**Comment by shea256** [comment]
![home 1x](https://cloud.githubusercontent.com/assets/994646/26030045/012b5620-3814-11e7-8328-2e9347d074ad.png)

**Comment by shea256** [comment]
![home 1x](https://cloud.githubusercontent.com/assets/994646/26030764/89f7d6ac-382a-11e7-8c7d-39e422da9895.png)

**Comment by shea256** [comment]
## A New Internet for Decentralized Apps

Blockstack is a new decentralized internet where users own their data and apps run locally. A browser portal is all that’s needed to get started.

Users
Join the Waitlist

Developers
Developer Toolkit

71861 users registered
3+ years in production
2716 community devs

## The Old Internet is Broken

#### Mass Data Breaches
Traditional apps store user data in massive data silos. This results in high value targets just waiting to be breached. With a single app, confidence in the safety of your data requires blind trust in dozens of companies.

#### Identity Theft
Traditional apps hold the digital keys to your identity and unlock your account when you provide your password and mother’s maiden name. This makes them vulnerable to password cracking and social engineering.

#### Platform Lock-in
Traditional apps lock you in. Users can’t migrate to new software. Individual companies are gatekeepers on innovation. Developers are restricted from anything that threatens their business model.

## The New Internet is Here

#### Own Your Data
With Blockstack apps you truly own your data. It’s kept on your device and encrypted before backed up in the cloud. This removes the need for blind trust in 3rd parties and makes it easier to keep your data safe.

#### Own Your Identity
With Blockstack apps you are in control of your identity. Your digital keys are seamlessly generated and kept on your device. There are no passwords, no servers to sign in to, and no trusted identity brokers.

#### Own Your Apps
Blockstack apps put users in control of their software. Apps live on user devices and utilize open source. Developers can build competing clients on the same network and users can easily switch.

## A Full Stack for Decentralized Apps

(diagram)

## Libraries and Step-by-Step Tutorials

Complete the step-by-step tutorials and see how easy it is to build decentralized, serverless apps in a few lines of code.

#### Identity
blockstack.redirectUserToSignIn()
blockstack.signUserIn((user) => {})

#### Storage (coming soon)
blockstack.putFile("settings.txt", {})
  .then(success => {})
blockstack.getFile("settings.txt")
  .then(data => {})

#### Payments (coming soon)
blockstack.getPaymentInfo("werner.id")
  .then(data => {})
blockstack.sendMoney("werner.id")
  .then(success => {})

Try the tutorials

## Thousands of New App Possibilities

#### Decentralized Social Networks
Existing social networks lock in users and limit access. Build a decentralized social network that allows users to own their relationships and data and take it with them wherever they go.

#### Peer-to-Peer Marketplaces
Existing marketplaces take a massive haircut and limit what can be bought and sold. Build a peer-to-peer marketplace that allows individuals to freely transact at a lower cost.

#### Community-Run Voting
Existing voting systems are centrally operated and thus are extremely vulnerable to hacking. Build a voting system as a public internet utility that’s run by the community instead of a single corporation.

## News

(news)

## Get Started

Users
Join the Waitlist

Developers
Developer Toolkit

**Comment by shea256** [comment]
![home 1x](https://cloud.githubusercontent.com/assets/994646/26030796/3de59202-382c-11e7-99fb-26badc95ed90.png)

**Comment by guylepage3** [comment]
Closing this issue. Locking in content for until after consensus
