### ISSUE TITLE
create process for pull requests

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#322]
Seems as though we are forgetting about PR's at times. or that they are taking quite a long time to get pushed live.

There is a need to set up a quick pull request process on the core dev side to resolve this issue. This will more likely enable more contributions on the blockstack.org and browser.

**Comment by vsund** [comment]
Would make a great part of the community review that appeared as idea in Slack 👍

**Comment by guylepage3** [comment]
@estermer here's the issue for your PR https://github.com/blockstack/blockstack.org/pull/330

**Comment by estermer** [comment]
Since we talked about it. There is a two step review. First to design then to master to push live. I suggest at Sprint meetings, open prs are discussed, and who will do the initial review and made a priority. Then after that I am not sure on what timeframe the master review is done and merged. Ok what do you think?

**Comment by guylepage3** [comment]
>I suggest at Sprint meetings, open prs are discussed, and who will do the initial review and made a priority. Then after that I am not sure on what timeframe the master review is done and merged.

@estermer, that's a possibility. 

cc:ing @shea256

**Comment by larrysalibra** [comment]
> I suggest at Sprint meetings, open prs are discussed, and who will do the initial review and made a priority.

PRs are issues like any other issue. If they're to be addressed during a particular sprint, then they should be added to the list of issues "To Do" for that sprint.

In general, repo maintainers should be responsible for commenting on incoming PRs (and all issues for that matter!) in a timely manner so that people's contributions and feedback isn't being ignored.

Clearly defining repo maintainers will help with this.

**Comment by estermer** [comment]
That's sounds great. I can add the repo maintainer to the contributing guide if you think it would be helpful?

**Comment by guylepage3** [comment]
>In general, repo maintainers should be responsible for commenting on incoming PRs (and all issues for that matter!) in a timely manner so that people's contributions and feedback isn't being ignored.

>Clearly defining repo maintainers will help with this.

For sure. We have the blockstack.org repo maintainers defined and feedback is fairly quick but could use more improvement.

PR's on the other hand naturally take a bit more time. We've been working on the speed at which they get addressed but that could also use improvement.

>That's sounds great. I can add the repo maintainer to the contributing guide if you think it would be helpful?

That works. For blockstack.org it is myself for the `design` branch. @shea256 then does the merge into the `master` branch.

**Comment by guylepage3** [comment]
@estermer lets move the repository maintainers to the bottom.

Also let's take a look how bootstrap handles their pull request contribution guidelines
- https://github.com/twbs/bootstrap/issues/new
- https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md

**Comment by estermer** [comment]
Ok i will review that documentation and see what can be integrated

**Comment by estermer** [comment]
@guylepage3 I looked into those two resources to see if there are any further additions I could make. few were made but it was good to iron it out and cross reference other useful contributing guidelines.

**Comment by guylepage3** [comment]
@estermer great work on this.. very cool! 👍

i'll take a look this afternoon and provide you with some feedback. i did see a broken link and also some of the instructions said "blockstack-portal." will provide more feedback later.

**Comment by guylepage3** [comment]
@estermer now that we have everyone doing their pull request from the `design` branch the merge process will speed up. that was a fairly smooth merge of the install mobile fix.

**Comment by vsund** [comment]
GitHub has some great resources on these topics, i.e.

* https://opensource.guide
* https://help.github.com/categories/building-a-strong-community/

**Comment by guylepage3** [comment]
Ok @estermer I see a couple of items to be adjusted with your PR:

1. Title should read "Contributing to Blockstack.org"
2. "Table of Contents" (TOC) "Blockstack Brand Guide" should actually be included into the "Pull Request" section as the first item that the contributor should review. Let's remove it from the TOC.
3. Put my name first under "Maintainers" as contributors will pull from my branch first.
4. "Project Boards" link under "Finding opportunities to contribute" is a dead link. Should link to the projects board for that repository.
5. "Issue Tracker" link under "Finding opportunities to contribute" is a dead link. Should link to the issue tracker for that repository.
6. "issue tracker" link under "Using the issue tracker" is a dead link. Should link to the issue tracker for that repository.
7. Under "Bug Reports" change "... latest `master` or development branch in the repository." to "... latest `master`, `design` or development branch in the repository."
8. Under "Pull Request" — There will be a new process where the contributor pulls from a branch called `contribute`. this will allow the maintainers of the repo to use any branch they please. maintainers will push their code to the `contribute` branch frequently.

**Comment by estermer** [comment]
Here is what I have for the pull request process as of right now as per suggestions from resources and conversations in designs, slack, and .org repo:

## Pull requests

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)

Good pull requests—patches, improvements, new features—are a fantastic help. They should remain focused in scope and avoid containing unrelated commits.

**Please ask first** before embarking on any significant pull request (e.g. implementing features, refactoring code, porting to a different language), otherwise you risk spending a lot of time working on something that the project's developers might not want to merge into the project.

Ensure that your pull requests are small components. This assists both with your pull request getting accepted and makes it much easier/faster for the repository maintainer to merge in your pull request.

Please adhere to the [Blockstack Brand Guide](https://github.com/blockstack/designs/issues/247), [coding guidelines](#code-guidelines) used throughout the project (indentation, accurate comments, etc.), and any other requirements (such as test coverage).

When contributing to Blockstack's documentation, you should edit the documentation source files in [the `/app/` directory of the `master` branch](https://github.com/blockstack/blockstack.org/tree/master/app).

Adhering to the following process is the best way to get your work included in the project:

1. [Fork](https://help.github.com/fork-a-repo/) the project, clone your fork,
   and configure the remotes:

   ```bash
   # Clone your fork of the repo into the current directory
   git clone https://github.com/<your-username>/blockstack.org.git
   # Navigate to the newly cloned directory
   cd blockstack.org
   # Assign the original repo to a remote called "upstream"
   git remote add upstream https://github.com/blockstack/blockstack.org.git
   ```

2. If you cloned a while ago, get the latest changes from the `contribute` branch upstream:

   ```bash
   git checkout -b contribute
   git pull upstream contribute
   ```

3. Create a new topic branch (off the main project development branch) to
   contain your feature, change, or fix, followed by semantic versioning
   using your Github username and 'patch':

   ```bash
   git checkout -b <topic-branch-name>-<github-username>-patch
   ```

4. Commit your changes in logical chunks. Please adhere to these [git commit
   message guidelines](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)
   or your code is unlikely be merged into the main project. Use Git's
   [interactive rebase](https://help.github.com/articles/interactive-rebase)
   feature to tidy up your commits before making them public.

5. Locally merge the upstream `contribute` branch into your topic branch:

   ```bash
   git pull upstream contribute
   ```

6. Push your topic branch up to your fork:

   ```bash
   git push origin <topic-branch-name>-<github-username>-patch
   ```

7. [Open a Pull Request](https://help.github.com/articles/using-pull-requests/) against the `design` branch.a
    - Add a clear title and description
    - Include screenshots of the before and after if your changes include differences in HTML/CSS. Drag and drop the images into the body of your pull request.
    - Reference any relevant issues or supporting documentation in your PR (ex. “Closes #37.”)
    - Make sure submitted code has no conflicts

**IMPORTANT**: By submitting a patch, you agree to allow the project owners to
license your work under the terms of the [MPL-2.0 License](https://github.com/blockstack/blockstack-browser/blob/master/LICENSE.md) (if it
includes code changes) and under the terms of the
[Creative Commons Attribution 3.0 Unported License](docs/LICENSE.md)
(if it includes documentation changes).

[^ Back To The Top](#contributing-to-blockstackorg)

**Comment by guylepage3** [comment]
This is awesome @estermer. one thing i see is that we will not be using `contribute` but the latest MINOR release number. i.e. `v4.3`, `v4.4`, etc.

**Comment by estermer** [comment]
aaaaaah ok so that is what you meant. That is an easy fix. That also shouldn't change the flow of the PR process for a contributor. I think it is a little more intuitive as well, better than a generic branch.

**Comment by guylepage3** [comment]
Awesome! Let's try dog fooding this process and see where we go wrong and/or where we can improve it.

@estermer you up for testing this bad boy out? Add a simple comment `/* testing by @estermer */` to the `main.css` file. And then execute a pull request.

**Comment by estermer** [comment]
Perfect will do

**Comment by guylepage3** [comment]
I'm excited for this... 😄

**Comment by vsund** [comment]
> one thing i see is that we will not be using contribute but the latest MINOR release number. i.e. v4.3, v4.4, etc.

This would be easier with an (advanced) branching model such as [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) (which has i.e. a branch with the latest stable version). As whole it may raise the barrier to contribute, but Contributors could ignore and just use the `master` branch (additionally there are [tools](https://github.com/petervanderdoes/gitflow-avh) to make things easier).

When executed properly you wouldn't have problems like "Which branch should I pull from?" (which I saw a few times in Slack :)).

**Comment by guylepage3** [comment]
Thanks for that link @vsund. Our goals with our git flow is two fold;
1. Make it as easy as possible for developers to contribute
2. Make it as easy and frictionless as possible for the repository maintainers to merge in contributors work.

It is very important for both goals to be met as best we can so that more contributions get submitted and pushed through as quickly as possible. The git flow link you've provided above seems to add complexity to the process. However, if you'd like to take @estermer's pull request flow and modify it we definitely would encourage that. Maybe it would assist us in seeing a better and faster way.

**Comment by estermer** [comment]
As I am understanding it, the current process has a production ready branch (master) and that the versioning branch (in the current case 4.0.0) would just be the "development" branch that everyone would pull from, make contributions, and submit a PR to. Once the updates have been made then the maintainers would review the version before merging to master and push to production, then creating a new version branch (4.1.0) where contributors can then pull, contribute, and PR to. 

This might just be an extra step always creating a versioned branch and tracking down the current development version. It might just be easier to name the branch development and the time of wanting to create a version and merge it to master. the Maintainers can create the new version branch to review as a whole before merging to master to then push to production.

This is what I got from perusing through the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) from @vsund. 

So this would be my suggested flow:

1. contributor forks repo
2. clones there fork locally and adds an upstream to blockstack's repo
3. contributor creates a branch called development and pulls from upstream development.
4. contributor creates their branch with their `topic-githubhandle-patch`
5. makes edits
6. pulls from development upstream to clear any potential merge conflicts
7. pushes to their fork
8. submits the PR with base branch being development
9. Maintainer reviews PR, if accepted -  merge to development
10. when ready for a release, maintainer created a version branch off development
11. maintainer reviews version branch
12 maintainer merges to master and pushes to production, merges master into development

What do you think @guylepage3 @vsund?

**Comment by vsund** [comment]
Sounds good 👍

The only thing I miss: Having feature-related branches when contributing. This helps core developers as well as other contributors to focus on a single feature/fix/improvement.

I know that trying apply git-flow seems hard but I think it worth trying (the command line tool is doing great work with preserving flow). But it's understandable that contributors could get confused by this (although it's not strictly needed to use git-flow everywhere).

**Comment by guylepage3** [comment]
Great work here @estermer and @vsund. 👍 

Let's think about this flow a bit more. I'd also like to get @jcnelson @shea256 @kantai's opinion on this as well.

**Comment by larrysalibra** [comment]
I think the [git-flow branching model](http://nvie.com/posts/a-successful-git-branching-model/) @vsund proposed is pretty good..I’d be happy going with that with a small change: 

I think it’s important to see what other people are working on. The post says that feature/topic branches should only live on developer machines.

I would propose is that feature/topic branches of core developers (those with commit access) live in `origin` (to use the terminology of the post) and that we introduce namespacing of such branches that include the github issue number being worked on.

For example branch `issue-123-optimize-requests` would correspond to github ticket #123. I’d also like to see people including the github issue number in their commit messages so that they get linked to issues.

**Comment by vsund** [comment]
The git-flow command line tool has the ability to publish feature branches to `origin` with `git flow feature publish <name>`. I fully agree that these branches should live in `origin` whenever it's possible.

👍 regarding issue numbers. You can even close issues with commit messages :D (accidentally did this some days ago)

**Comment by larrysalibra** [comment]
@vsund cool. i’ll give the git flow tool a try tomorrow. 

Ha! I also recently learned that you can close github pull requests by deleted the branch upon which the pull request is based. Not the behavior I’d expect!

**Comment by guylepage3** [comment]
@larrysalibra @vsund @estermer... This process seems to make a lot of sense.

@estermer why don't we give this a try and put it into the pull request process?

**Comment by estermer** [comment]
Looking into this today.

**Comment by estermer** [comment]
Did we want the development branch called `develop`? I noticed there already is a develop branch, do we want to make this the development branch they proposed in the git-flow process?

Also For the contributors I suggested creating a branch like this `git checkout -b issue-<issue number>-<branch topic>-<github username>`

I removed path from the end because it sort of is replaced with adding the issue number.

**Comment by larrysalibra** [comment]
@estermer have you tried out the `git flow` command?

It has tools to create the branches "automatically" 

```
Vanquish:blockstack.js larry$ git flow
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.

Try 'git flow <subcommand> help' for details.
Vanquish:blockstack.js larry$ git flow feature
No feature branches exist.

You can start a new feature branch:

    git flow feature start <name> [<base>]

Vanquish:blockstack.js larry$
```

**Comment by estermer** [comment]
ah i didn't realize it was a command line tool haha, I just read the post and it was talking about the process but not the tool lol

**Comment by vsund** [comment]
@estermer The author of this post started implementing a [tool](https://github.com/nvie/gitflow) for helping with that model, but the repository is more or less dead.
I strongly suggest using [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) (a fork that is well maintained and improved).

Also, when using issue numbers for branches, we could start requiring an issue respective every new feature/bugfix branch. Would be enable discussing on every development step we take, and additionally put the substance from names and commit messages into issues.

**Comment by estermer** [comment]
@vsund I found that tool you referenced and am adding it to the PR process.

**Comment by estermer** [comment]
@larrysalibra let me know what areas you think the current contributing guide does not match our needs.

**Comment by guylepage3** [comment]
Looks as though we can close this out. 

@estermer?

**Comment by vsund** [comment]
Just read how this all began:
> Seems as though we are forgetting about PR's at times. or that they are taking quite a long time to get pushed live.

I created an issue yesterday that now seems related: https://github.com/blockstack/blockstack/issues/327. How and when reviews are handled can still get improved :)

**Comment by guylepage3** [comment]
@vsund, @estermer has completed our new contribution guideline for this repository, blockstack.org and we are now implementing that as of this past Thursday.

@estermer will be going around and completing a similar guideline for each repository which should make things very clear and easier for repository maintainers to quickly review, accept or deny pull requests.

Closing this issue.

**Comment by vsund** [comment]
Yeah, this is a bit different from having guidelines, i proposed to have a scheduled review to process new issues / pull requests more efficient (see there :)).

**Comment by guylepage3** [comment]
i feel by changing the process and making it less friction for the maintainer we've resolved this and from now on we just need to be on top of the maintainer for that particular repository to check on a "daily" basis for pull requests.

there does not need to be a schedule for this. it should be a daily thing for maintainers. that's just the way it is.

let's be diligent and steadfast in letting the maintainers know that there are pull requests to look at. this is an open source community. if you want to maintain a repo. you need to review once per day, everyday. it's that simple.
