### ISSUE TITLE
Add page-specific meta data

### ISSUE THREAD

**Issue by arisgk** [blockstack/blockstack.org#368]
Currently, meta data are bound to our [build process](https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/copyIndex.js). As a result, served meta data are the same for all our routes.

We could follow an approach similar to the one [create-react-app](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#generating-dynamic-meta-tags-on-the-server) suggests in order to serve page-specific meta data. It would require some server-side work.

**Comment by shea256** [comment]
Earlier, I integrated React Helmet (https://github.com/nfl/react-helmet) but this only updates the metadata after the page loads. One thing we could do is have the gulp scripts pre-render the metadata based on what's in the helmet tags. This would be similar to what the scripts currently do for pre-rendering HTML files for blog posts.

This would also be a relevant method to us since we're using a static hosting server: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#pre-rendering-into-static-html-files. That said, it seems to be more of a change from what we're doing currently.

My recommendation would be to re-integrate React Helmet and put a helmet tag on every single page. Then, the next step would be to create a script that builds html files from each of the pages. This would be similar to what you see here for the blog posts: https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/buildDocs.js.

**Comment by guylepage3** [comment]
>My recommendation would be to re-integrate React Helmet and put a helmet tag on every single page. Then, the next step would be to create a script that builds html files from each of the pages. This would be similar to what you see here for the blog posts: https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/buildDocs.js.

Awesome. Thank you @shea256.

@arisgk can you give this a try?

**Comment by arisgk** [comment]
> My recommendation would be to re-integrate React Helmet and put a helmet tag on every single page. Then, the next step would be to create a script that builds html files from each of the pages. This would be similar to what you see here for the blog posts: https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/buildDocs.js.

@shea256, @guylepage3 I like this approach too. I made some research and the only thing I am thinking about this combined with what [create-react-app suggests](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#pre-rendering-into-static-html-files) is that we are going to build something like [react-snapshot](https://www.npmjs.com/package/react-snapshot), which renders HTML files during the build & deployment phase. So we could explore if using react-snapshot would work well or even rewire the web app to use `create-react-app` (it would be trivial to integrate react-snapshot then and it could make the project more easily maintainable). It's a tradeoff actually, if we want it to be built quickly we can follow the blog-posts approach initially. Let me know about your preference on this and I will give it a try.

**Comment by guylepage3** [comment]
Awesome work @arisgk 😄 

@shea256 what are your thoughts on this?

**Comment by guylepage3** [comment]
@shea256 are you working on this issue at the moment?
