### ISSUE TITLE
Can't sign in/sign up with Blockstack on forum.blockstack.org

### ISSUE THREAD

**Issue by dhealy05** [blockstack/blockstack.org#392]
All options on the forum to sign in or sign up with Blockstack seem to be broken--they variously redirect to the error message "Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?" or a 500 error. 

I have a registered Blockstack ID and have v .15 installed.

**Comment by markmhx** [comment]
I'm reopening this after a report today in Slack by Samuel Cole, who pointed out the behavior was also reported in the forum as recently as November 2018: https://forum.blockstack.org/t/forum-login-is-broken/6646

**Comment by moxiegirl** [comment]
@markmhx did you try this yourself to confirm it was an issue?

**Comment by markmhx** [comment]
@moxiegirl I've almost certainly run into this error message before, though I can't remember just when it happened last, and I seem to remember that the error message itself was erroneous (in that after seeing it and navigating to the forum homepage, I was actually signed in).

I just tried to recreate by signing out and back in using the same browser, and I didn't encounter the problem. So I'm unable to recreate myself at the moment.

**Comment by markmhx** [comment]
Actually, I just tried the sign in flow again and noticed that when I clicked "Sign In", a new tab opened with my local Blockstack Browser for the auth flow, and the original tab with the forum redirected to this screen:

<img width="849" alt="screen shot 2019-02-21 at 11 50 05" src="https://user-images.githubusercontent.com/28991/53163644-d7b4db80-35ce-11e9-9762-33ea8a43c9b9.png">

If I click "Connect" here instead of using the new tab that opens with the Browser, then I _do_ see this error message instantly:

<img width="853" alt="screen shot 2019-02-21 at 11 50 40" src="https://user-images.githubusercontent.com/28991/53163686-ef8c5f80-35ce-11e9-9d39-0954810ca9e0.png">

Perhaps this is the same experience encountered by others (who try to use that "Connect" button), or perhaps there's a different path to the error message. I wonder, for example, if users without the local Browser installed will get directed to the above page within the same tab within certain cases, given protocol handling considerations.

cc'ing @zone117x in case something comes quickly to mind for him here

**Comment by zone117x** [comment]
This page seems broken and needs updated to latest blockstack.js https://forum.blockstack.org/auth/blockstack

Login still works for me but that original tab shows an error.

**Comment by hstove** [comment]
That 'connect' button is generated explicitly by the omniauth library, and it's meant for OAuth-style integrations that do server-side auth. We need to just modify that page to remove the 'connect' button.

**Comment by neurotarun** [comment]
Unable to sign in to forum with my existing blockstack id  . This is a recent issue in both chrome and firefox browser . 
![bugstack](https://user-images.githubusercontent.com/5704414/90433062-19b5c500-e080-11ea-8269-1f9587a0f1c5.png)

**Comment by larrysalibra** [comment]
it looks like someone added a restrictive content security policy to the forum that breaks sign in with blockstack id.

```
Content-Security-Policy: base-uri 'none'; object-src 'none'; script-src https://forum.blockstack.org/logs/ https://forum.blockstack.org/sidekiq/ https://forum.blockstack.org/mini-profiler-resources/ https://forum.blockstack.org/assets/ https://forum.blockstack.org/brotli_asset/ https://forum.blockstack.org/extra-locales/ https://forum.blockstack.org/highlight-js/ https://forum.blockstack.org/javascripts/ https://forum.blockstack.org/plugins/ https://forum.blockstack.org/theme-javascripts/ https://forum.blockstack.org/svg-sprite/ https://www.google-analytics.com/analytics.js; worker-src 'self' blob:
```

If i recall correctly, inline scripts need to be enabled.

Maybe @wileyj can help?

**Comment by CharlieC3** [comment]
@wileyj I'm reading that it's possible Cloud Flare could cause this issue as well? Either way, I don't see any `Content-Security-Policy` headers being explicitly set in our k8s scripts. Will keep looking.

**Comment by wileyj** [comment]
cc @ryanarndtcm 
no config type changes have been made to the forum in a long while, we think this is an internal forum policy that's been triggered. looking into if that's the case here.
