### ISSUE TITLE
Add Telegram link to our website 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#540]

**Comment by larrysalibra** [comment]
Removal of this link in the current version of the website has significantly slowed down the growth of the telegram group. Was growing 10-20 people a day before and since the update only growing by 1-2 a day.  Link is: https://t.me/BlockstackChat for English and https://t.me/BlockstackChinese for Chinese

**Comment by markmhx** [comment]
I've confirmed these links are back in the footer on staging for https://github.com/blockstack/blockstack.org/pull/640.

<img width="714" alt="screen shot 2018-08-30 at 11 40 20" src="https://user-images.githubusercontent.com/28991/44843841-952acb80-ac49-11e8-8aff-d4ed5454a0a8.png">
