### ISSUE TITLE
Improve UX in browser install page

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#567]
I'm in the middle of documenting how to get the browser and create a blockstack id --- a formal doc. In doing so, I thought of a few ways to improve the layout and information on the https://blockstack.org/install page. What I think is important:

- Clarify the title --- I don't think users are installing "Blockstack" unless we define it solely as the browser.
- Provide a brief definition of the browser for users
- Clarify what users need to move forward as separate from what a developer requires.
- Remove any outdated information such as the "limited capability" note
- Things which launch browser actions should be buttons -- things which are not are links.

My suggested changes appear in this mockup:

![image](https://user-images.githubusercontent.com/1347209/42515824-a697d4cc-842a-11e8-9037-69b331e0e842.png)

**Comment by aulneau** [comment]
Comments from Slack ->

I don’t know if downloading the browser === building dapps. I think people who download the browser want more security and to have things run locally vs on a server they have no visibility in.

**Comment by aulneau** [comment]
Generally with decentralized apps, being able to run them locally gives people less concern than using an app that is on a server. I think others could probably weigh in better than I can about the exact details of why it's better. You can have better insight into the requests that something locally makes compared to something on a server. Something on a server would probably be considered more centralized than something running locally.

**Comment by jehunter5811** [comment]
Good question. I think at some point @xanbots told me that Blockstack's analytics show similar worldwide spread to what I'm seeing with Graphite. Here's the distribution of users hitting the Graphite log in page: 

<img width="986" alt="screen shot 2018-07-10 at 10 02 26 am" src="https://user-images.githubusercontent.com/10519834/42518894-7b80e23a-8428-11e8-801f-7f21e96af7c8.png">

That equates to more than 50% of users visiting Graphite being outside the United States. I think decentralization is a novelty for folks in the States and for folks in other relatively open countries. However, in most of the rest of the world, decentralization is a solution to a real problem. That problem is largely censorship in the forms of blocking sites, intimidating users, prison, and death in some cases. 

To me, Blockstack's current maturity actually supports the censorship-resistance side of things far better than it supports any other uses.

**Comment by yknl** [comment]
Given that we have feature parity between the Blockstack browser web app and the native apps, it would make sense to remove the "Limited capability" tag in the download page. We should also put it above the native versions since it's a much easier way to get started. However, I don't think we should label it as being for developers, because there are many reasons why someone would want to run a native app than just for developing dapps.

**Comment by moxiegirl** [comment]
@jehunter5811 @yknl @jeffdomke I discovered this morning that I can't open a Dapp without launching the local browser. That means the browser application acts more like a local, enabling client (think chat/conference app like Skype)  for a Dapp rather than an alternative version of the web browser.  So, I've adjusted the page accordingly:

![image](https://user-images.githubusercontent.com/1347209/42955967-8e710782-8b33-11e8-9ef0-8804c1865b7b.png)

**Comment by jehunter5811** [comment]
@moxiegirl I don't think that's accurate. I think what you're running into is that if you have a local version of the browser running, you will be automatically routed through that for authentication. Whereas if you don't have the local browser downloaded, you will have the option to download it or use the web app.

**Comment by moxiegirl** [comment]
@jeffdomke I was running the webapp, I selected a Dapp, and when I went to use it, it launched my local version of the browser.  Here is an example of what I saw with each App I attempted to launch.

![image](https://user-images.githubusercontent.com/1347209/43010139-720b02c0-8bf4-11e8-83c3-d18b2d2bb302.png)

If I don't' choose the app, the system simply cancels my request to sign in.

Now, it could be the Dapp making the request for the local app.  Perhaps these are mobile apps, but there is no way to tell from the presentation on the Browser page. And, was it the case that some of these apps don't work on desktops, I would expect the page to filter what it presents me based on the device I'm on or something.

Of course, I haven't tested every individual app...four seemed sufficient at the moment.

**Comment by moxiegirl** [comment]
@jehunter5811 Thanks for the reply. That test ^^ shown above was run with no browser installed locally. Just to confirm, I ran removed everything and tried it again. Same result.

![image](https://user-images.githubusercontent.com/1347209/43014622-a115bf30-8c01-11e8-9b81-2d35bed5c12d.png)

Perhaps the removal is flawed? I'm currently running through the uninstall, the procedure I'm following is documented on my fork here:

https://github.com/moxiegirl/blockstack/blob/tutorial-fix/tutorials/browser-introduction.md#on-mac-1

**Comment by moxiegirl** [comment]
@jehunter5811 Dang it, the dmg was mounted even though the App was deleted. I hate that. Once I ejected the mounts it worked as you said. Thank you for spending some time to help me figure this out.  I'll add a check for the mount to my procedure.

**Comment by jehunter5811** [comment]
No problem! This is why I rarely end up testing the web app browser. It's just too difficult to uninstall the local browser and re-install. BrowserStack has been helpful when I do want to test the web app browser, though.

**Comment by moxiegirl** [comment]
@jehunter5811 It occurs to me that a better UX is not to ask, IOW, if I launch from the Web browser, sign in with the Web browser; if I launch from local open in local.  It seems an obvious win from a user's perspective.
