### ISSUE TITLE
Improve copy of confirmation email

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#596]
![Screen Shot 2018-07-24 at 3:59 PM](http://marker.screenshots.prod.s3.amazonaws.com/3874698880c64da08b1ff9527ff23ace-1532447975129.png)
---
### More Info

**Source URL**: [https://inbox.google.com/u/0/?cid=imp&pli=1](https://inbox.google.com/u/0/?cid=imp&pli=1)

**Comment by aulneau** [comment]
I don't have access to change this. Maybe someone from growth can. cc @xanbots @pstan26

**Comment by cuevasm** [comment]
I don't control this email - I don't know where it's coming from. @yknl any ideas?

**Comment by yknl** [comment]
I don't know where this is coming from. It looks like it was sent in 2018, is that still being sent? It kind of looks like the email you get when you subscribe to the newsletter from the 2017 version of blockstack.org.

**Comment by cuevasm** [comment]
I've confirmed this was sent to Jeff in 2018, I can see the record in MailChimp. I imagine that was generated when someone signed up for Blockstack from the browser or on the old site. Given MailChimp is turned off, I don't believe there's any way for someone to get this message currently. 

Go forward plan: New users should be offered a checkbox optin at the time of email submission in the browser setup process. Otherwise, I'm not comfortable adding them to a mailing list and don't think that would be right by our devs. If we put that in place, users can be sent directly to Mailigen and new subscribers will automatically get a welcome email that is vastly improved over this one. Those that are opting in on the website are already having this experience.
