### ISSUE TITLE
Very loud indicator/button after I'm done with it. Can we make it go away after 10 seconds, etc. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#597]
![Screen Shot 2018-07-24 at 4:01 PM](http://marker.screenshots.prod.s3.amazonaws.com/86128b27f7bd40f4a2825be4668285be-1532448061440.png)
---
### More Info

**Source URL**: [https://blockstackorgv2.netlify.com/tutorials/hello-blockstack/](https://blockstackorgv2.netlify.com/tutorials/hello-blockstack/)

**Comment by markmhx** [comment]
@aulneau Is this the new confirmation message that replaces the loud one indicated by @jeffdomke?

<img width="696" alt="screen shot 2018-08-30 at 11 26 21" src="https://user-images.githubusercontent.com/28991/44843085-c0acb680-ac47-11e8-9158-9aef23e640f1.png">

I don't see either a "Tutorials" button or "Thanks for subscribing!" at the top of the viewport as shown in his screenshot anymore, so I'm  presuming this screenshot represents the new approach but not entirely sure.

**Comment by markmhx** [comment]
Never mind, I see now that there's a fixed navigation with these two buttons upon scrolling back up a page. And when I submit an email on staging for https://github.com/blockstack/blockstack.org/pull/640, the input restores to its default state after a few seconds:

## Immediately after submit

<img width="669" alt="screen shot 2018-08-30 at 11 48 19" src="https://user-images.githubusercontent.com/28991/44844250-a88a6680-ac4a-11e8-8d0b-5a3abe67a0fc.png">

## Few seconds later

<img width="664" alt="screen shot 2018-08-30 at 11 49 16" src="https://user-images.githubusercontent.com/28991/44844277-bdff9080-ac4a-11e8-80fe-7c69980c9dac.png">

–––

That font in the confirmation state, though, appears different than the one used in the default state (and on the page in general). Can we standardize that? Same goes for the "Processing..." state right before confirmation.

## Side note

The whole interaction around this scroll-up triggered fix navigation seems a bit finicky to me. I think that's due to both:

- If I scroll up and then just a little bit back down again, it goes away very quickly
- If I scroll up to near the top of the page, this navigation goes away 

This is probably for another issue or two, but I may recommend we tone down the interactions for hiding this navigation so it doesn't feel so fleeting.

**Comment by aulneau** [comment]
@markmhx typeface issues fixed with https://github.com/blockstack/blockstack.org/commit/ca4f6a9f6a9ed6a78a6aeae66bee5ffd811773f1
