### ISSUE TITLE
[Home, Technology] Events data

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#784]
We have this section on a couple pages:

<img width="1079" alt="Screen Shot 2019-05-03 at 4 30 48 PM" src="https://user-images.githubusercontent.com/11803153/57166778-dcf98800-6dc0-11e9-9ba7-aef3ede1b3ba.png">

Currently we cannot pull event data from an API to render these. We either need to determine somewhere to host this data, remove this section, or hardcode the data.

**Comment by aulneau** [comment]
@cuevasm Can you put together a list of the top 6 events coming up in the next six months or so? we will hardcode the events for this component in for now.

**Comment by cuevasm** [comment]
Actually I mentioned that this data can be pulled, just not RSS (which is what you requested initially). The feed of these events is available from a standard Google feed. 

Public URL: https://calendar.google.com/calendar/embed?src=9r3bpuvm3sbhi8a92djdm9hs97tm7e9k%40import.calendar.google.com&ctz=America%2FLos_Angeles
Public, ICS format: https://calendar.google.com/calendar/ical/9r3bpuvm3sbhi8a92djdm9hs97tm7e9k%40import.calendar.google.com/public/basic.ics
Timely: http://events.time.ly/06hh9ge/export?format=ics&no_html=true

There's this build in subscribe thing too, which is I believe how the Google Calendar Blockstack Events gets its data:
![image](https://user-images.githubusercontent.com/6131188/57413876-bf566500-71aa-11e9-890b-b9a9456e5c9c.png)

If none of these work, happy to move from this, I've investigated some other options. I defer to @shanvoight on picking top 6 events for now.

**Comment by aulneau** [comment]
@cuevasm I think based off of time needs, we should hardcode these events in for now, just the top/high profile events we going to have in the coming months. I was going to put together a little script to convert the .ics to .json so I can use it, but there is very little ability to filter these events.

**Comment by cuevasm** [comment]
Got it, I still defer to @shanvoight for selecting the top events. When do you imagine this goes live? (So we don't pick ones that become immediately stale)

**Comment by cuevasm** [comment]
The other option is to pull a carousel of our meetups, they have an API. Let me know if you can see this, https://www.meetup.com/meetup_api/

**Comment by shanvoight** [comment]
@aulneau Let me know if you need anything else:

1. Consensus - May 13-15, 2019
2. Digital Asset Summit - May 15, 2019
3. Token Summit - May 16, 2019
4. DevDay Berlin - May 25, 2019
5. CogX London - June 10-12, 2019
6. RISE Hong Kong - July 8-11, 2019
7. JS Camp Barcelona - July 18-29, 2019

**Comment by aulneau** [comment]
@shanvoight sorry I think this won't go live before june 1, so if we could have all big events (6 or so) that are happening june onwards that'd be great! Thank you!

**Comment by shanvoight** [comment]
@aulneau sorry about that - here you go: 

1. CogX London - June 10-12, 2019
2. JS Camp Barcelona - July 18-29, 2019

**Comment by shanvoight** [comment]
Hey @aulneau it doesnt look like my last entry was posted due to the wifi at Consensus. Here is the latest list but with a few new additions. Please let me know if you need anything else. Thanks!

1. June 1: Bangalore: [Blockstack Bangalore Meetup with SpringRole](https://www.meetup.com/Blockstack-Bangalore/events/261247907/) 
2. June 3: Remote: ['Can't Be Evil' webinar with Xan Ditkoff](https://www.crowdcast.io/e/cant-be-evil-contest-4/register)
3. June 4: Brighton, UK: [Radicle (Blockstack Dapp) @ Brighton and Blockchain meetup](https://www.meetup.com/Brighton-Blockchain-Meetup/events/261104312/)
4. June 6: NYC: [NYC Blockchain Devs meetup with Blockstack](https://www.meetup.com/nyc-blockchain-devs/events/)
5. June 10-12: London: [CogX] with Brittany Laughlin and Justin Hunter (https://cogx.co/)
6. June 13: NYC: [NYC Blockchain Devs meetup with Blockstack](https://www.meetup.com/nyc-blockchain-devs/events/)
7. June 24: SF: Women Lvl up meetup with Gina Abrams
8. June 26: NYC: [Javascript NYC + Blockstack](https://www.meetup.com/JS-NYC/events/261289323/)
9. July 18-19: Barcelona: [JS Camp](https://jscamp.tech/) with Matt Little
10. August 15: NYC: [React NYC Meetup with Blockstack](https://www.meetup.com/ReactNYC/events/259414202/)
11. August 19-21: Berlin: [Web3 Summit](https://web3summit.com/) with Mark Hendrickson
