### ISSUE TITLE
[Homepage] Build apps: not immediately clear the case studies relate to app developers

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#945]

**Comment by jasperjansz** [comment]
There is an alternative design for this: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1393%3A12632

If you guys agree this is a superior solution please assign to yourself @aulneau

**Comment by jeffdomke** [comment]
I like this solution, not sure it is the best we can do. I see 3 hierarchies of text and 2 CTAS all squished into this panel when I look at it I kind of think "too much stuff... skip" wonder if we can organize and break up in such a way that it invites more parsing. 

Also, I'm not following how this problem is stated. "not immediately clear the case studies relate to app developers" – I don't remember this as the problem here. Can we align on the exact problem please? 

![Screen Shot 2019-07-11 at 8.34.18 AM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/fc0d5ea8-d879-42bd-8970-fdf81a251ec8)

Not clear that Graphite is a Blockstack app? 
Too much focus on Justin, not Graphite? 
The section has no title?
